package com.tsi.training.gilliland.charlie.cocktailrecipes.selenium;
// Generated by Selenium IDE

import com.tsi.training.gilliland.charlie.cocktailrecipes.selenium.pages.glass.CreateGlassPage;
import com.tsi.training.gilliland.charlie.cocktailrecipes.selenium.pages.glass.ViewGlassPage;
import com.tsi.training.gilliland.charlie.cocktailrecipes.selenium.pages.utility.Navigation;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;


public class CreateGlassTest {
  WebDriver driver;
  Navigation nav;
  CreateGlassPage createGlassPage;
  ViewGlassPage viewGlassPage;
  String type = "Selenium Type";
  String volume = "50";

  @Test
  public void createGlass() {
    // Setting up driver and pages
    driver = CreateWebDriver.localDriver();
    nav = new Navigation(driver);
    createGlassPage = new CreateGlassPage(driver);
    viewGlassPage = new ViewGlassPage(driver);

    // Use these when posting to jenkins
//    System.setProperty("webdriver.chrome.driver", "/usr/bin/chromedriver");
//    ChromeOptions options = new ChromeOptions();
//    options.addArguments("headless");
//    options.addArguments("disable-gpu");
//    driver = new ChromeDriver(options);

    // Opening site and navigating to the correct page
    driver.get("http://localhost:3000/");
    nav.navigateToCreateGlass();
    Assertions.assertEquals("http://localhost:3000/createGlass", driver.getCurrentUrl());

    // Creating the glass
    createGlassPage.enterType(type);
    createGlassPage.enterVolume(volume);
    createGlassPage.clickCreateButton();
    Assertions.assertEquals("http://localhost:3000/glasses", driver.getCurrentUrl());

    // Checking the element has been added
    driver.navigate().refresh();
    driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
    Assertions.assertTrue(viewGlassPage.checkForEntry(type, volume));
    driver.close();
  }
}
