package com.tsi.training.gilliland.charlie.cocktailrecipes.selenium;
// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;


@Ignore
public class CreateGlassTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createGlass() {
    driver.get("https://main.d3fprs5bjp2a56.amplifyapp.com/");
    driver.manage().window().setSize(new Dimension(1294, 1040));
    driver.findElement(By.linkText("Create")).click();
    driver.findElement(By.linkText("Glass")).click();
    driver.findElement(By.id("glassTypeInput")).click();
    driver.findElement(By.id("glassTypeInput")).sendKeys("Selenium Test");
    driver.findElement(By.id("glassVolumeInput")).click();
    driver.findElement(By.id("glassVolumeInput")).sendKeys("200");
    driver.findElement(By.cssSelector(".contentContainer")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.linkText("Glass")).click();
    driver.close();
  }
}
