package com.tsi.training.gilliland.charlie.cocktailrecipes.selenium;
// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.HashMap;
import java.util.Map;
public class NavigationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriver driver;
    System.setProperty("webdriver.chrome.driver", "/usr/bin/chromedriver");
    ChromeOptions options = new ChromeOptions();
    options.addArguments("headless");
    options.addArguments("disable-gpu");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void navigation() {
    driver.get("https://main.d3fprs5bjp2a56.amplifyapp.com/");
    driver.manage().window().setSize(new Dimension(1583, 1040));
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.linkText("Cocktails")).click();
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.linkText("Equipment")).click();
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.cssSelector(".nav-link:nth-child(4) > .darkText")).click();
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.cssSelector(".nav-link:nth-child(5) > .darkText")).click();
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.linkText("Glass")).click();
    driver.findElement(By.linkText("Create")).click();
    driver.findElement(By.cssSelector(".nav-link:nth-child(1) > .darkText")).click();
    driver.findElement(By.linkText("Create")).click();
    driver.findElement(By.cssSelector(".nav-link:nth-child(3) > .darkText")).click();
    driver.findElement(By.linkText("Create")).click();
    driver.findElement(By.cssSelector(".nav-link:nth-child(4) > .darkText")).click();
    driver.findElement(By.linkText("Create")).click();
    driver.findElement(By.linkText("Garnish")).click();
    driver.findElement(By.linkText("Create")).click();
    driver.findElement(By.linkText("Glass")).click();
    driver.findElement(By.linkText("Nice Cocktail")).click();
    driver.close();
  }
}
