package com.tsi.training.gilliland.charlie.cocktailrecipes.selenium;
// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;

public class SearchTest {
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Test
  public void search() {
    WebDriver driver;
    System.setProperty("webdriver.chrome.driver", "/usr/bin/google-chrome");
    ChromeOptions options = new ChromeOptions();
    options.addArguments("headless");
    driver = new ChromeDriver(options);
    driver.get("https://main.d3fprs5bjp2a56.amplifyapp.com/");
    driver.manage().window().setSize(new Dimension(1294, 1040));
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.cssSelector(".nav-link:nth-child(3) > .darkText")).click();
    driver.findElement(By.cssSelector(".searchInput")).click();
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.cssSelector(".nav-link:nth-child(4) > .darkText")).click();
    driver.findElement(By.cssSelector(".searchInput")).click();
    driver.findElement(By.cssSelector(".searchInput")).sendKeys("coke");
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.linkText("Garnish")).click();
    driver.findElement(By.cssSelector(".searchInput")).click();
    driver.findElement(By.cssSelector(".searchInput")).sendKeys("or");
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.linkText("Glass")).click();
    driver.findElement(By.cssSelector(".searchInput")).click();
    driver.close();
    driver.quit();
  }
}
