package com.tsi.training.gilliland.charlie.cocktailrecipes.selenium;
// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

@Ignore
public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void search() {
    driver.get("https://main.d3fprs5bjp2a56.amplifyapp.com/");
    driver.manage().window().setSize(new Dimension(1294, 1040));
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.cssSelector(".nav-link:nth-child(3) > .darkText")).click();
    driver.findElement(By.cssSelector(".searchInput")).click();
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.cssSelector(".nav-link:nth-child(4) > .darkText")).click();
    driver.findElement(By.cssSelector(".searchInput")).click();
    driver.findElement(By.cssSelector(".searchInput")).sendKeys("coke");
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.linkText("Garnish")).click();
    driver.findElement(By.cssSelector(".searchInput")).click();
    driver.findElement(By.cssSelector(".searchInput")).sendKeys("or");
    driver.findElement(By.linkText("View")).click();
    driver.findElement(By.linkText("Glass")).click();
    driver.findElement(By.cssSelector(".searchInput")).click();
    driver.close();
  }
}
